import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/ui/Sidebar";
import firebase, { FirebaseContext } from "../firebase/firebase";
import {collection, addDoc } from 'firebase/firestore';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className + " flex"}>
       
          <div className="flex-none">
            <Sidebar />
          </div>
          <div className="flex-1 ml-4">
            {children}
          </div>
       
      </body>
    </html>
  );
}
